name: send alerts for nearby fires
on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

env: 
  AWS_ID: ${{ secrets.AWS_ID }}
  AWS_SECRET: ${{ secrets.AWS_SECRET }}
  API_URL: ${{ secrets.API_URL }}
  TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
  TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
  TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
  TEST_PHONE_NUMBER: ${{ secrets.TEST_PHONE_NUMBER }}

jobs:
  get_fire_alerts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - run: npm install
      - run: npm install playwright-chromium
      - run: yarn get-latest-fires
      - run: yarn wait
      - run: yarn identify-matches
      - run: yarn update-timestamp
      - uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          add_options: last-updated.txt

